USE [master]
GO

/****** Object:  Database [SalesOfMaterial]    Script Date: 21.06.2024 19:13:05 ******/
CREATE DATABASE [SalesOfMaterial]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SalesOfMaterial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SalesOfMaterial.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SalesOfMaterial_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SalesOfMaterial_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SalesOfMaterial].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SalesOfMaterial] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET ARITHABORT OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SalesOfMaterial] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SalesOfMaterial] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SalesOfMaterial] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SalesOfMaterial] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SalesOfMaterial] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SalesOfMaterial] SET  MULTI_USER 
GO

ALTER DATABASE [SalesOfMaterial] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SalesOfMaterial] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SalesOfMaterial] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SalesOfMaterial] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SalesOfMaterial] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SalesOfMaterial] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SalesOfMaterial] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SalesOfMaterial] SET  READ_WRITE 
GO


